### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by paf31** [paf31/purescript-coroutines#25]
I'm listed as maintainer, but maybe I shouldn't be. I think this is used in Halogen, so maybe someone who uses Halogen would like to maintain this?

**Comment by garyb** [comment]
I think @natefaubion had previously said he'd be up for maintaining this.

**Comment by paf31** [comment]
Sounds good to me - if you're still interested, Nate, let me know, and I'll add you as collaborator.

**Comment by natefaubion** [comment]
Sure, I'd be happy to.

**Comment by paf31** [comment]
Looks like you've been made contributor already. I made you admin, so I'll close this, and update the badge. Thanks!
